- name: Update ubuntu servers
  hosts: u2
  become: yes

  tasks:
  - name: install apache2
    package:
      name: apache2
      state: present

  - name: start apache2
    service:
      name: apache2
      state: started

  - name: enable apache2
    service:
      name: apache2
      enabled: yes


